// ISO 3166-1 alpha-2 → numeric (for matching world-atlas topojson `id` property)
// and display name. Flag emoji is computed from the iso2 regional indicators.

export function flagFor(iso2: string): string {
  const c = (iso2 || '').toUpperCase()
  if (c.length !== 2 || !/^[A-Z]{2}$/.test(c)) return '🌐'
  return String.fromCodePoint(
    0x1F1E6 - 65 + c.charCodeAt(0),
    0x1F1E6 - 65 + c.charCodeAt(1),
  )
}

// iso2 → { name, numericId (3-digit ISO 3166-1 numeric, as string) }
// Names are picked to match world-atlas@2 topojson property names where possible,
// so the globe can also match via `properties.name` as a fallback.
export const COUNTRIES: Record<string, { name: string; numericId: string }> = {
  AD: { name: 'Andorra', numericId: '020' },
  AE: { name: 'United Arab Emirates', numericId: '784' },
  AF: { name: 'Afghanistan', numericId: '004' },
  AG: { name: 'Antigua and Barbuda', numericId: '028' },
  AI: { name: 'Anguilla', numericId: '660' },
  AL: { name: 'Albania', numericId: '008' },
  AM: { name: 'Armenia', numericId: '051' },
  AO: { name: 'Angola', numericId: '024' },
  AQ: { name: 'Antarctica', numericId: '010' },
  AR: { name: 'Argentina', numericId: '032' },
  AS: { name: 'American Samoa', numericId: '016' },
  AT: { name: 'Austria', numericId: '040' },
  AU: { name: 'Australia', numericId: '036' },
  AW: { name: 'Aruba', numericId: '533' },
  AX: { name: 'Åland Islands', numericId: '248' },
  AZ: { name: 'Azerbaijan', numericId: '031' },
  BA: { name: 'Bosnia and Herzegovina', numericId: '070' },
  BB: { name: 'Barbados', numericId: '052' },
  BD: { name: 'Bangladesh', numericId: '050' },
  BE: { name: 'Belgium', numericId: '056' },
  BF: { name: 'Burkina Faso', numericId: '854' },
  BG: { name: 'Bulgaria', numericId: '100' },
  BH: { name: 'Bahrain', numericId: '048' },
  BI: { name: 'Burundi', numericId: '108' },
  BJ: { name: 'Benin', numericId: '204' },
  BL: { name: 'Saint Barthélemy', numericId: '652' },
  BM: { name: 'Bermuda', numericId: '060' },
  BN: { name: 'Brunei', numericId: '096' },
  BO: { name: 'Bolivia', numericId: '068' },
  BQ: { name: 'Caribbean Netherlands', numericId: '535' },
  BR: { name: 'Brazil', numericId: '076' },
  BS: { name: 'Bahamas', numericId: '044' },
  BT: { name: 'Bhutan', numericId: '064' },
  BV: { name: 'Bouvet Island', numericId: '074' },
  BW: { name: 'Botswana', numericId: '072' },
  BY: { name: 'Belarus', numericId: '112' },
  BZ: { name: 'Belize', numericId: '084' },
  CA: { name: 'Canada', numericId: '124' },
  CC: { name: 'Cocos (Keeling) Islands', numericId: '166' },
  CD: { name: 'Dem. Rep. Congo', numericId: '180' },
  CF: { name: 'Central African Republic', numericId: '140' },
  CG: { name: 'Congo', numericId: '178' },
  CH: { name: 'Switzerland', numericId: '756' },
  CI: { name: "Côte d'Ivoire", numericId: '384' },
  CK: { name: 'Cook Islands', numericId: '184' },
  CL: { name: 'Chile', numericId: '152' },
  CM: { name: 'Cameroon', numericId: '120' },
  CN: { name: 'China', numericId: '156' },
  CO: { name: 'Colombia', numericId: '170' },
  CR: { name: 'Costa Rica', numericId: '188' },
  CU: { name: 'Cuba', numericId: '192' },
  CV: { name: 'Cape Verde', numericId: '132' },
  CW: { name: 'Curaçao', numericId: '531' },
  CX: { name: 'Christmas Island', numericId: '162' },
  CY: { name: 'Cyprus', numericId: '196' },
  CZ: { name: 'Czechia', numericId: '203' },
  DE: { name: 'Germany', numericId: '276' },
  DJ: { name: 'Djibouti', numericId: '262' },
  DK: { name: 'Denmark', numericId: '208' },
  DM: { name: 'Dominica', numericId: '212' },
  DO: { name: 'Dominican Republic', numericId: '214' },
  DZ: { name: 'Algeria', numericId: '012' },
  EC: { name: 'Ecuador', numericId: '218' },
  EE: { name: 'Estonia', numericId: '233' },
  EG: { name: 'Egypt', numericId: '818' },
  EH: { name: 'Western Sahara', numericId: '732' },
  ER: { name: 'Eritrea', numericId: '232' },
  ES: { name: 'Spain', numericId: '724' },
  ET: { name: 'Ethiopia', numericId: '231' },
  FI: { name: 'Finland', numericId: '246' },
  FJ: { name: 'Fiji', numericId: '242' },
  FK: { name: 'Falkland Islands', numericId: '238' },
  FM: { name: 'Micronesia', numericId: '583' },
  FO: { name: 'Faroe Islands', numericId: '234' },
  FR: { name: 'France', numericId: '250' },
  GA: { name: 'Gabon', numericId: '266' },
  GB: { name: 'United Kingdom', numericId: '826' },
  GD: { name: 'Grenada', numericId: '308' },
  GE: { name: 'Georgia', numericId: '268' },
  GF: { name: 'French Guiana', numericId: '254' },
  GG: { name: 'Guernsey', numericId: '831' },
  GH: { name: 'Ghana', numericId: '288' },
  GI: { name: 'Gibraltar', numericId: '292' },
  GL: { name: 'Greenland', numericId: '304' },
  GM: { name: 'Gambia', numericId: '270' },
  GN: { name: 'Guinea', numericId: '324' },
  GP: { name: 'Guadeloupe', numericId: '312' },
  GQ: { name: 'Equatorial Guinea', numericId: '226' },
  GR: { name: 'Greece', numericId: '300' },
  GS: { name: 'South Georgia and South Sandwich Is.', numericId: '239' },
  GT: { name: 'Guatemala', numericId: '320' },
  GU: { name: 'Guam', numericId: '316' },
  GW: { name: 'Guinea-Bissau', numericId: '624' },
  GY: { name: 'Guyana', numericId: '328' },
  HK: { name: 'Hong Kong', numericId: '344' },
  HM: { name: 'Heard Island and McDonald Islands', numericId: '334' },
  HN: { name: 'Honduras', numericId: '340' },
  HR: { name: 'Croatia', numericId: '191' },
  HT: { name: 'Haiti', numericId: '332' },
  HU: { name: 'Hungary', numericId: '348' },
  ID: { name: 'Indonesia', numericId: '360' },
  IE: { name: 'Ireland', numericId: '372' },
  IL: { name: 'Israel', numericId: '376' },
  IM: { name: 'Isle of Man', numericId: '833' },
  IN: { name: 'India', numericId: '356' },
  IO: { name: 'British Indian Ocean Territory', numericId: '086' },
  IQ: { name: 'Iraq', numericId: '368' },
  IR: { name: 'Iran', numericId: '364' },
  IS: { name: 'Iceland', numericId: '352' },
  IT: { name: 'Italy', numericId: '380' },
  JE: { name: 'Jersey', numericId: '832' },
  JM: { name: 'Jamaica', numericId: '388' },
  JO: { name: 'Jordan', numericId: '400' },
  JP: { name: 'Japan', numericId: '392' },
  KE: { name: 'Kenya', numericId: '404' },
  KG: { name: 'Kyrgyzstan', numericId: '417' },
  KH: { name: 'Cambodia', numericId: '116' },
  KI: { name: 'Kiribati', numericId: '296' },
  KM: { name: 'Comoros', numericId: '174' },
  KN: { name: 'Saint Kitts and Nevis', numericId: '659' },
  KP: { name: 'North Korea', numericId: '408' },
  KR: { name: 'South Korea', numericId: '410' },
  KW: { name: 'Kuwait', numericId: '414' },
  KY: { name: 'Cayman Islands', numericId: '136' },
  KZ: { name: 'Kazakhstan', numericId: '398' },
  LA: { name: 'Laos', numericId: '418' },
  LB: { name: 'Lebanon', numericId: '422' },
  LC: { name: 'Saint Lucia', numericId: '662' },
  LI: { name: 'Liechtenstein', numericId: '438' },
  LK: { name: 'Sri Lanka', numericId: '144' },
  LR: { name: 'Liberia', numericId: '430' },
  LS: { name: 'Lesotho', numericId: '426' },
  LT: { name: 'Lithuania', numericId: '440' },
  LU: { name: 'Luxembourg', numericId: '442' },
  LV: { name: 'Latvia', numericId: '428' },
  LY: { name: 'Libya', numericId: '434' },
  MA: { name: 'Morocco', numericId: '504' },
  MC: { name: 'Monaco', numericId: '492' },
  MD: { name: 'Moldova', numericId: '498' },
  ME: { name: 'Montenegro', numericId: '499' },
  MF: { name: 'Saint Martin', numericId: '663' },
  MG: { name: 'Madagascar', numericId: '450' },
  MH: { name: 'Marshall Islands', numericId: '584' },
  MK: { name: 'North Macedonia', numericId: '807' },
  ML: { name: 'Mali', numericId: '466' },
  MM: { name: 'Myanmar', numericId: '104' },
  MN: { name: 'Mongolia', numericId: '496' },
  MO: { name: 'Macao', numericId: '446' },
  MP: { name: 'Northern Mariana Islands', numericId: '580' },
  MQ: { name: 'Martinique', numericId: '474' },
  MR: { name: 'Mauritania', numericId: '478' },
  MS: { name: 'Montserrat', numericId: '500' },
  MT: { name: 'Malta', numericId: '470' },
  MU: { name: 'Mauritius', numericId: '480' },
  MV: { name: 'Maldives', numericId: '462' },
  MW: { name: 'Malawi', numericId: '454' },
  MX: { name: 'Mexico', numericId: '484' },
  MY: { name: 'Malaysia', numericId: '458' },
  MZ: { name: 'Mozambique', numericId: '508' },
  NA: { name: 'Namibia', numericId: '516' },
  NC: { name: 'New Caledonia', numericId: '540' },
  NE: { name: 'Niger', numericId: '562' },
  NF: { name: 'Norfolk Island', numericId: '574' },
  NG: { name: 'Nigeria', numericId: '566' },
  NI: { name: 'Nicaragua', numericId: '558' },
  NL: { name: 'Netherlands', numericId: '528' },
  NO: { name: 'Norway', numericId: '578' },
  NP: { name: 'Nepal', numericId: '524' },
  NR: { name: 'Nauru', numericId: '520' },
  NU: { name: 'Niue', numericId: '570' },
  NZ: { name: 'New Zealand', numericId: '554' },
  OM: { name: 'Oman', numericId: '512' },
  PA: { name: 'Panama', numericId: '591' },
  PE: { name: 'Peru', numericId: '604' },
  PF: { name: 'French Polynesia', numericId: '258' },
  PG: { name: 'Papua New Guinea', numericId: '598' },
  PH: { name: 'Philippines', numericId: '608' },
  PK: { name: 'Pakistan', numericId: '586' },
  PL: { name: 'Poland', numericId: '616' },
  PM: { name: 'Saint Pierre and Miquelon', numericId: '666' },
  PN: { name: 'Pitcairn', numericId: '612' },
  PR: { name: 'Puerto Rico', numericId: '630' },
  PS: { name: 'Palestine', numericId: '275' },
  PT: { name: 'Portugal', numericId: '620' },
  PW: { name: 'Palau', numericId: '585' },
  PY: { name: 'Paraguay', numericId: '600' },
  QA: { name: 'Qatar', numericId: '634' },
  RE: { name: 'Réunion', numericId: '638' },
  RO: { name: 'Romania', numericId: '642' },
  RS: { name: 'Serbia', numericId: '688' },
  RU: { name: 'Russia', numericId: '643' },
  RW: { name: 'Rwanda', numericId: '646' },
  SA: { name: 'Saudi Arabia', numericId: '682' },
  SB: { name: 'Solomon Islands', numericId: '090' },
  SC: { name: 'Seychelles', numericId: '690' },
  SD: { name: 'Sudan', numericId: '729' },
  SE: { name: 'Sweden', numericId: '752' },
  SG: { name: 'Singapore', numericId: '702' },
  SH: { name: 'Saint Helena', numericId: '654' },
  SI: { name: 'Slovenia', numericId: '705' },
  SJ: { name: 'Svalbard and Jan Mayen', numericId: '744' },
  SK: { name: 'Slovakia', numericId: '703' },
  SL: { name: 'Sierra Leone', numericId: '694' },
  SM: { name: 'San Marino', numericId: '674' },
  SN: { name: 'Senegal', numericId: '686' },
  SO: { name: 'Somalia', numericId: '706' },
  SR: { name: 'Suriname', numericId: '740' },
  SS: { name: 'South Sudan', numericId: '728' },
  ST: { name: 'São Tomé and Príncipe', numericId: '678' },
  SV: { name: 'El Salvador', numericId: '222' },
  SX: { name: 'Sint Maarten', numericId: '534' },
  SY: { name: 'Syria', numericId: '760' },
  SZ: { name: 'Eswatini', numericId: '748' },
  TC: { name: 'Turks and Caicos Islands', numericId: '796' },
  TD: { name: 'Chad', numericId: '148' },
  TF: { name: 'French Southern Territories', numericId: '260' },
  TG: { name: 'Togo', numericId: '768' },
  TH: { name: 'Thailand', numericId: '764' },
  TJ: { name: 'Tajikistan', numericId: '762' },
  TK: { name: 'Tokelau', numericId: '772' },
  TL: { name: 'Timor-Leste', numericId: '626' },
  TM: { name: 'Turkmenistan', numericId: '795' },
  TN: { name: 'Tunisia', numericId: '788' },
  TO: { name: 'Tonga', numericId: '776' },
  TR: { name: 'Turkey', numericId: '792' },
  TT: { name: 'Trinidad and Tobago', numericId: '780' },
  TV: { name: 'Tuvalu', numericId: '798' },
  TW: { name: 'Taiwan', numericId: '158' },
  TZ: { name: 'Tanzania', numericId: '834' },
  UA: { name: 'Ukraine', numericId: '804' },
  UG: { name: 'Uganda', numericId: '800' },
  US: { name: 'United States of America', numericId: '840' },
  UY: { name: 'Uruguay', numericId: '858' },
  UZ: { name: 'Uzbekistan', numericId: '860' },
  VA: { name: 'Vatican', numericId: '336' },
  VC: { name: 'Saint Vincent and the Grenadines', numericId: '670' },
  VE: { name: 'Venezuela', numericId: '862' },
  VG: { name: 'British Virgin Islands', numericId: '092' },
  VI: { name: 'U.S. Virgin Islands', numericId: '850' },
  VN: { name: 'Vietnam', numericId: '704' },
  VU: { name: 'Vanuatu', numericId: '548' },
  WF: { name: 'Wallis and Futuna', numericId: '876' },
  WS: { name: 'Samoa', numericId: '882' },
  YE: { name: 'Yemen', numericId: '887' },
  YT: { name: 'Mayotte', numericId: '175' },
  ZA: { name: 'South Africa', numericId: '710' },
  ZM: { name: 'Zambia', numericId: '894' },
  ZW: { name: 'Zimbabwe', numericId: '716' },
}

export const NUMERIC_TO_ISO2: Record<string, string> = Object.fromEntries(
  Object.entries(COUNTRIES).map(([iso2, { numericId }]) => [numericId, iso2])
)

export const TOTAL_COUNTRIES = Object.keys(COUNTRIES).length

export function nameFor(iso2: string): string {
  return COUNTRIES[(iso2 || '').toUpperCase()]?.name ?? iso2
}
