import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  safelist: [
    'min-h-screen',
    'flex',
    'items-center',
    'justify-center',
    'px-4',
    'w-full',
    'max-w-sm',
    'block',
    'text-center',
    'mb-8',
    'mb-6',
    'mb-4',
    'mb-1',
    'mb-1.5',
    'mt-6',
    'mt-3',
    'mt-4',
    'mt-5',
    'my-5',
    'p-8',
    'px-3.5',
    'py-2.5',
    'py-3',
    'gap-3',
    'gap-2.5',
    'flex-1',
    'h-px',
    'space-y-4',
    'bg-snow',
    'bg-white',
    'bg-haze',
    'bg-red-50',
    'bg-earth-700',
    'bg-earth-800',
    'text-ink',
    'text-slate',
    'text-earth-700',
    'text-earth-800',
    'text-white',
    'text-sunset',
    'text-xl',
    'text-sm',
    'text-xs',
    'text-2xl',
    'border',
    'border-fog',
    'border-red-200',
    'border-earth-400',
    'ring-2',
    'ring-earth-300',
    'rounded-2xl',
    'rounded-lg',
    'rounded-full',
    'shadow-sm',
    'font-semibold',
    'font-medium',
    'font-bold',
    'font-display',
    'hover:bg-haze',
    'hover:bg-earth-800',
    'hover:bg-gray-50',
    'hover:underline',
    'focus:outline-none',
    'focus:ring-2',
    'focus:border-earth-400',
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
    'transition-colors',
  ],
  content: [
    './src/app/**/*.{ts,tsx}',
    './src/components/**/*.{ts,tsx}',
    './src/lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        earth: {
          50:  'var(--earth-50)',
          100: 'var(--earth-100)',
          300: 'var(--earth-300)',
          500: 'var(--earth-500)',
          700: 'var(--earth-700)',
          800: 'var(--earth-800)',
          900: 'var(--earth-900)',
          DEFAULT: 'var(--earth-800)',
        },
        sand: {
          100: 'var(--sand-100)',
          500: 'var(--sand-500)',
          700: 'var(--sand-700)',
          DEFAULT: 'var(--sand-700)',
        },
        sky: {
          100: 'var(--sky-100)',
          500: 'var(--sky-500)',
          800: 'var(--sky-800)',
          DEFAULT: 'var(--sky-800)',
        },
        sunset: {
          100: 'var(--sunset-100)',
          500: 'var(--sunset-500)',
          700: 'var(--sunset-700)',
          DEFAULT: 'var(--sunset-700)',
        },
        ink: 'var(--color-ink)',
        primary: 'var(--color-primary)',
        accent: 'var(--color-accent)',
        surface: 'var(--color-surface)',
        navy: 'var(--color-navy)',
        slate: 'var(--slate)',
        ash:   'var(--ash)',
        mist:  'var(--mist)',
        fog:   'var(--fog)',
        haze:  'var(--haze)',
        snow: 'var(--color-snow)',
      },
      fontFamily: {
        display: ['-apple-system', 'BlinkMacSystemFont', 'SF Pro Display', 'system-ui', 'sans-serif'],
        body:    ['-apple-system', 'BlinkMacSystemFont', 'SF Pro Text', 'system-ui', 'sans-serif'],
        mono:    ['Fira Code', 'Cascadia Code', 'monospace'],
      },
      fontSize: {
        'xs':   ['0.6875rem', { lineHeight: '1rem' }],
        'sm':   ['0.8125rem', { lineHeight: '1.25rem' }],
        'base': ['0.9375rem', { lineHeight: '1.6' }],
        'lg':   ['1.0625rem', { lineHeight: '1.5' }],
        'xl':   ['1.1875rem', { lineHeight: '1.4' }],
        '2xl':  ['1.375rem',  { lineHeight: '1.3' }],
        '3xl':  ['1.75rem',   { lineHeight: '1.2' }],
        '4xl':  ['2.25rem',   { lineHeight: '1.1' }],
        '5xl':  ['2.75rem',   { lineHeight: '1.05' }],
      },
      borderRadius: {
        'sm':   'var(--radius-sm)',
        DEFAULT: 'var(--radius-md)',
        'md':   'var(--radius-md)',
        'lg':   'var(--radius-lg)',
        'xl':   'var(--radius-xl)',
        '2xl':  'var(--radius-2xl)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        'sm':  'var(--shadow-sm)',
        'md':  'var(--shadow-md)',
        'lg':  'var(--shadow-lg)',
        'xl':  'var(--shadow-xl)',
        'gps': '0 0 0 4px var(--earth-100)',
      },
      transitionDuration: {
        'fast':  'var(--dur-fast)',
        'base':  'var(--dur-base)',
        'slow':  'var(--dur-slow)',
        'enter': 'var(--dur-enter)',
      },
      transitionTimingFunction: {
        'out':    'var(--ease-out)',
        'spring': 'var(--ease-spring)',
        'smooth': 'var(--ease-smooth)',
      },
      spacing: {
        'nav': 'var(--nav-h)',
      },
      maxWidth: {
        'feed': 'var(--max-w-feed)',
        'page': 'var(--max-w-page)',
        'wide': 'var(--max-w-wide)',
      },
      keyframes: {
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to:   { opacity: '1', transform: 'scale(1)' },
        },
        'pulse-gps': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgb(76 175 128 / 0.4)' },
          '50%':      { boxShadow: '0 0 0 8px rgb(76 175 128 / 0)' },
        },
        'slide-in-right': {
          from: { opacity: '0', transform: 'translateX(16px)' },
          to:   { opacity: '1', transform: 'translateX(0)' },
        },
      },
      animation: {
        'fade-up':        'fade-up 420ms cubic-bezier(0,0,0.2,1) both',
        'fade-in':        'fade-in 350ms cubic-bezier(0,0,0.2,1) both',
        'scale-in':       'scale-in 200ms cubic-bezier(0.34,1.56,0.64,1) both',
        'pulse-gps':      'pulse-gps 2s ease-in-out infinite',
        'slide-in-right': 'slide-in-right 350ms cubic-bezier(0,0,0.2,1) both',
      },
    },
  },
  plugins: [],
}

export default config
