import type { Metadata } from 'next'
import Link from 'next/link'
import { getTenant } from '@/lib/get-tenant'

export async function generateMetadata(): Promise<Metadata> {
  const tenant = await getTenant()
  return {
    title: 'Terms & Conditions',
    description: `Terms and conditions governing your use of ${tenant.name}.`,
    alternates: { canonical: `https://${tenant.host}/terms/` },
  }
}

const C = { bg: '#f3f4f6', text: '#111827', body: '#374151', sub: '#6b7280', teal: 'var(--brand)' }

export default async function TermsPage() {
  const tenant = await getTenant()
  const brand = tenant.name
  const host = tenant.host
  const lastUpdated = 'April 2026'
  return (
    <main style={{ background: C.bg, minHeight: '100vh' }}>
      <div style={{ maxWidth: 820, margin: '0 auto', padding: '56px 24px 80px' }}>
        <h1 style={{ fontFamily: 'Georgia, serif', fontSize: 'clamp(28px, 4.5vw, 42px)', fontWeight: 800, margin: '0 0 8px', color: C.text }}>Terms &amp; Conditions</h1>
        <p style={{ fontSize: 13, color: C.sub, margin: '0 0 32px' }}>Last updated: {lastUpdated}</p>

        <div style={{ fontSize: 16, color: C.body, lineHeight: 1.75 }}>
          <p>These Terms govern your use of <b>{brand}</b> ({host}). By using the site, creating an account, or booking a tour through us, you agree to these Terms.</p>

          <H2>Using {brand}</H2>
          <p>You must be at least 13 years old to create an account. You agree to provide accurate information and keep your password secure. You&rsquo;re responsible for activity that occurs under your account.</p>

          <H2>Tour bookings</H2>
          <p>{brand} displays tours and experiences offered by third-party operators (including Viator and its suppliers). When you click through to book, you&rsquo;re contracting directly with that operator under their cancellation, refund and liability terms, which are shown at checkout. {brand} is not a party to those contracts and cannot modify them. Prices and availability shown on {brand} are indicative and confirmed on the operator&rsquo;s booking page.</p>

          <H2>Caravan park &amp; destination listings</H2>
          <p>We aggregate publicly available information about caravan parks, holiday parks, tourist parks and destinations. Details including pricing, amenities and site types can change — please confirm directly with the park before travelling.</p>

          <H2>User content</H2>
          <p>If you submit content (reviews, questions, photos), you grant {brand} a non-exclusive licence to display and distribute it on the site. You keep ownership of what you post. Don&rsquo;t post content that&rsquo;s illegal, misleading, or infringes anyone else&rsquo;s rights; we may remove content that violates these Terms.</p>

          <H2>Intellectual property</H2>
          <p>The {brand} site, layout, and non-user-generated text are © {new Date().getFullYear()} {brand}. Tour descriptions may be generated by our systems and are covered by our copyright; images remain the property of their original owners and are used with permission or under licence.</p>

          <H2>Disclaimer</H2>
          <p>{brand} is provided &ldquo;as is&rdquo;. We work hard to keep information accurate, but we don&rsquo;t guarantee it&rsquo;s free of errors. To the maximum extent permitted by law, {brand} excludes liability for indirect, incidental or consequential loss arising from your use of the site.</p>

          <H2>Australian Consumer Law</H2>
          <p>Nothing in these Terms excludes, restricts or modifies any right or remedy guaranteed under the Australian Consumer Law (ACL). If you&rsquo;re a consumer under the ACL, our products and services come with guarantees that can&rsquo;t be excluded.</p>

          <H2>Changes</H2>
          <p>We&rsquo;ll post updates here and refresh the &ldquo;last updated&rdquo; date above. Continued use of {brand} after changes are posted means you accept the new Terms.</p>

          <H2>Contact</H2>
          <p>Use our <Link href="/contact/" style={{ color: C.teal }}>contact form</Link>.</p>

          <p style={{ marginTop: 32, fontSize: 14, color: C.sub }}>See also our <Link href="/privacy/" style={{ color: C.teal }}>Privacy Policy</Link> and <Link href="/cookies/" style={{ color: C.teal }}>Cookie Policy</Link>.</p>
        </div>
      </div>
    </main>
  )
}

function H2({ children }: { children: React.ReactNode }) {
  return <h2 style={{ fontFamily: 'Georgia, serif', fontSize: 22, fontWeight: 700, margin: '32px 0 12px', color: C.text }}>{children}</h2>
}
