-- Seed autravel.trains — Australia's passenger & scenic rail services.
-- Evergreen content only (routes, operators, classes) — no volatile prices/times.
-- Re-runnable: ON CONFLICT (slug) DO UPDATE.

INSERT INTO autravel.trains
  (slug, name, operator, operator_url, booking_url, state_codes, is_national, is_heritage,
   route_summary, from_city, to_city, key_stations, classes, frequency, duration_label,
   intro, body_html, legacy_article_slug, seo_title, seo_description, display_order)
VALUES
-- ─── NATIONAL — Journey Beyond Rail Expeditions ───────────────────────────────
('the-ghan', 'The Ghan', 'Journey Beyond', 'https://www.journeybeyondrail.com.au/journeys/the-ghan/',
 'https://www.journeybeyondrail.com.au/journeys/the-ghan/', ARRAY['sa','nt','aunz'], true, false,
 'Adelaide ↔ Darwin via Alice Springs', 'Adelaide', 'Darwin',
 ARRAY['Adelaide','Marla','Alice Springs','Katherine','Darwin'],
 ARRAY['Gold Service','Platinum Service'], 'Scheduled — twice weekly each way (seasonal)', '3 days / 2 nights',
 'One of the world''s great train journeys — a 2,979 km transcontinental crossing through the heart of Australia, from the Southern Ocean at Adelaide to the tropical Top End at Darwin.',
 '<p>The Ghan runs the length of the continent, linking Adelaide and Darwin through the Red Centre. The full expedition takes three days and two nights northbound, with the train pausing for Off Train Excursions at Alice Springs and Katherine (and Marla / Coober Pedy region southbound), so the journey is as much about what you step off to see as the scenery rolling past the window.</p><p>Accommodation is all-inclusive: <strong>Gold Service</strong> offers private single or twin cabins with ensuite options and meals in the Queen Adelaide Restaurant, while <strong>Platinum Service</strong> adds larger cabins, double beds and premium dining. All meals, drinks and Off Train Excursions are included in the fare.</p><p>The name honours the Afghan cameleers who opened up the inland routes long before the railway. Today the line is operated by Journey Beyond, who also run the Indian Pacific, Great Southern and The Overland. Departures are seasonal (roughly February–November) and book out well ahead, so reserve early.</p>',
 NULL, 'The Ghan — Adelaide to Darwin Train', 'Ride The Ghan across Australia — Adelaide to Darwin via Alice Springs & Katherine. Gold & Platinum service, all-inclusive. Routes, cabins & how to book.', 10),

('indian-pacific', 'Indian Pacific', 'Journey Beyond', 'https://www.journeybeyondrail.com.au/journeys/indian-pacific/',
 'https://www.journeybeyondrail.com.au/journeys/indian-pacific/', ARRAY['nsw','sa','wa','aunz'], true, false,
 'Sydney ↔ Perth via Adelaide, Broken Hill & the Nullarbor', 'Sydney', 'Perth',
 ARRAY['Sydney','Broken Hill','Adelaide','Cook','Kalgoorlie','Perth'],
 ARRAY['Gold Service','Platinum Service'], 'Scheduled — weekly each way (seasonal)', '4 days / 3 nights',
 'Coast to coast across Australia — 4,352 km from the Pacific at Sydney to the Indian Ocean at Perth, including the longest dead-straight stretch of railway track in the world across the Nullarbor Plain.',
 '<p>The Indian Pacific is one of the few train journeys in the world to cross an entire continent ocean to ocean. Over four days it climbs the Blue Mountains, crosses the outback to the silver-mining town of Broken Hill, calls at Adelaide, then runs the famous 478 km arrow-straight line across the treeless Nullarbor — pausing at the tiny siding of Cook — before reaching the goldfields at Kalgoorlie and finishing in Perth.</p><p>As with The Ghan, fares are all-inclusive across <strong>Gold</strong> and <strong>Platinum</strong> service, with private cabins, restaurant dining and Off Train Excursions at Broken Hill, Adelaide, Cook and Kalgoorlie. The exact excursions vary with the direction of travel and season.</p><p>Operated by Journey Beyond. Services run weekly in each direction during the season; cabins are limited and popular, so early booking is essential.</p>',
 NULL, 'Indian Pacific — Sydney to Perth Train', 'The Indian Pacific crosses Australia coast to coast — Sydney to Perth via Broken Hill, Adelaide & the Nullarbor. Gold & Platinum cabins, all-inclusive.', 20),

('great-southern', 'Great Southern', 'Journey Beyond', 'https://www.journeybeyondrail.com.au/journeys/great-southern/',
 'https://www.journeybeyondrail.com.au/journeys/great-southern/', ARRAY['sa','vic','nsw','qld','aunz'], true, false,
 'Adelaide ↔ Brisbane (summer seasonal)', 'Adelaide', 'Brisbane',
 ARRAY['Adelaide','Grampians region','Canberra','Coffs Harbour','Brisbane'],
 ARRAY['Gold Service','Platinum Service'], 'Seasonal — December to January only', '3–4 days',
 'A summer-only journey down the eastern seaboard between Adelaide and Brisbane, with Off Train Excursions through wine country, the Grampians, Canberra and the NSW coast.',
 '<p>The Great Southern is Journey Beyond''s newest expedition and runs only over the Australian summer (December–January). It links Adelaide and Brisbane, with the itinerary and excursions varying by direction — taking in highlights such as the Grampians, the Canberra region, the Coffs Harbour coast and the Hunter Valley depending on the departure.</p><p>Like its sister trains it is fully inclusive, with <strong>Gold</strong> and <strong>Platinum</strong> cabins, all dining and drinks, and signature Off Train Excursions. Because the season is so short, departures are very limited and sell out early.</p>',
 NULL, 'Great Southern — Adelaide to Brisbane Train', 'The Great Southern is a summer-only rail journey between Adelaide and Brisbane with coastal & wine-country excursions. Gold & Platinum, all-inclusive.', 30),

('the-overland', 'The Overland', 'Journey Beyond', 'https://www.journeybeyondrail.com.au/journeys/the-overland/',
 'https://www.journeybeyondrail.com.au/journeys/the-overland/', ARRAY['vic','sa','aunz'], true, false,
 'Melbourne ↔ Adelaide (daytime)', 'Melbourne', 'Adelaide',
 ARRAY['Melbourne','Geelong','Ararat','Murray Bridge','Adelaide'],
 ARRAY['Red Premium','Red Service'], 'Scheduled — daytime services each week', 'About 10½ hours',
 'One of Australia''s classic daytime trains, running between Melbourne and Adelaide across the western Victorian plains and the South Australian Mallee in a single day.',
 '<p>The Overland has linked Melbourne and Adelaide since 1887 and is one of the last great daytime intercity trains in the country. It crosses Victoria''s western districts, the Grampians plains and the Murray, arriving the same day. Seating is in <strong>Red Premium</strong> (wider seats, meals and drinks at your seat) or <strong>Red Service</strong>, with a café car aboard.</p><p>It''s a relaxed, scenic and good-value alternative to flying between the two cities, and connects with regional coach services at either end. Operated by Journey Beyond.</p>',
 NULL, 'The Overland — Melbourne to Adelaide Train', 'The Overland runs daytime between Melbourne and Adelaide across western Victoria. Red Premium & Red seating, café car. Route, classes & booking.', 40),

-- ─── QUEENSLAND — Queensland Rail Travel ─────────────────────────────────────
('spirit-of-queensland', 'Spirit of Queensland', 'Queensland Rail Travel', 'https://www.queenslandrailtravel.com.au/trains/spiritofqueensland',
 'https://www.queenslandrailtravel.com.au/', ARRAY['qld'], false, false,
 'Brisbane ↔ Cairns along the tropical coast', 'Brisbane', 'Cairns',
 ARRAY['Brisbane','Bundaberg','Rockhampton','Mackay','Townsville','Cairns'],
 ARRAY['RailBed (lie-flat)','Premium Economy seat'], 'Five services each way per week', 'About 25 hours',
 'Queensland Rail''s flagship tilt train hugs 1,681 km of tropical coastline between Brisbane and Cairns, with lie-flat RailBeds — the only ones of their kind in Australia.',
 '<p>The Spirit of Queensland runs five times a week in each direction between Brisbane and Cairns, calling at Bundaberg, Rockhampton, Mackay, Townsville and the coastal towns between. It''s a modern tilting train, so it takes the curves faster and rides smoothly.</p><p>The standout is <strong>RailBed</strong> class — premium seats that convert to fully flat beds for overnight travel, with a meal service included. <strong>Premium Economy</strong> offers reclining seats. There''s an onboard Club Car for meals and refreshments.</p>',
 'transport-queensland-rail-travel-train-timetables-spirit-of-queensland-1990',
 'Spirit of Queensland — Brisbane to Cairns Train', 'The Spirit of Queensland tilt train runs Brisbane to Cairns with lie-flat RailBeds. Route, stations, classes & how to book with Queensland Rail.', 50),

('spirit-of-the-outback', 'Spirit of the Outback', 'Queensland Rail Travel', 'https://www.queenslandrailtravel.com.au/trains/spiritoftheoutback',
 'https://www.queenslandrailtravel.com.au/', ARRAY['qld'], false, false,
 'Brisbane ↔ Longreach via Rockhampton', 'Brisbane', 'Longreach',
 ARRAY['Brisbane','Rockhampton','Emerald','Barcaldine','Longreach'],
 ARRAY['Sleeper','First Class seat','Economy seat'], 'Twice weekly each way', 'About 24 hours',
 'From the Brisbane coast deep into the central-west outback, the Spirit of the Outback links the capital with Longreach — home of the Stockman''s Hall of Fame and Qantas Founders Museum.',
 '<p>The Spirit of the Outback departs Brisbane twice a week, running up the coast to Rockhampton before turning inland through Emerald and Barcaldine to Longreach. It''s the classic way to reach Queensland''s outback country, with <strong>Sleeper</strong> cabins, <strong>First Class</strong> and <strong>Economy</strong> seating and the Tuckerbox dining car aboard.</p>',
 'transport-queensland-rail-travel-train-timetables-spirit-of-the-outback-2003',
 'Spirit of the Outback — Brisbane to Longreach', 'The Spirit of the Outback runs Brisbane to Longreach via Rockhampton. Sleeper cabins, dining car. Route, stations & booking with Queensland Rail.', 60),

('tilt-train', 'Electric Tilt Train', 'Queensland Rail Travel', 'https://www.queenslandrailtravel.com.au/trains/tilttrain',
 'https://www.queenslandrailtravel.com.au/', ARRAY['qld'], false, false,
 'Brisbane ↔ Rockhampton (high-speed coastal)', 'Brisbane', 'Rockhampton',
 ARRAY['Brisbane','Maryborough West','Bundaberg','Gladstone','Rockhampton'],
 ARRAY['Business Class','Economy Class'], 'Daily services', 'About 7½ hours to Rockhampton',
 'Australia''s fastest passenger train — the Electric Tilt Train reaches up to 160 km/h on its daily run up the central Queensland coast between Brisbane and Rockhampton.',
 '<p>The Electric Tilt Train is the quick way up the coast, with daily services from Brisbane to Bundaberg, Gladstone and Rockhampton. Tilting technology lets it hold higher speeds through curves, making it the fastest train in the country. Choose <strong>Business Class</strong> for wider seats and at-seat service or <strong>Economy</strong>, with a Café car aboard.</p>',
 'transport-queensland-rail-travel-train-timetables-tilt-train-1994',
 'Electric Tilt Train — Brisbane to Rockhampton', 'The Electric Tilt Train is Australia''s fastest — Brisbane to Rockhampton daily via Bundaberg & Gladstone. Business & Economy. Route & booking.', 70),

('the-westlander', 'The Westlander', 'Queensland Rail Travel', 'https://www.queenslandrailtravel.com.au/trains/westlander',
 'https://www.queenslandrailtravel.com.au/', ARRAY['qld'], false, false,
 'Brisbane ↔ Charleville (south-west outback)', 'Brisbane', 'Charleville',
 ARRAY['Brisbane','Toowoomba','Roma','Charleville'],
 ARRAY['Sleeper','Economy seat'], 'Twice weekly each way', 'About 17 hours',
 'The Westlander climbs the Great Dividing Range to Toowoomba and rolls out into the south-west mulga country, connecting Brisbane with Roma and Charleville.',
 '<p>The Westlander runs twice a week from Brisbane through Toowoomba and out to the western towns of Roma and Charleville, with connecting coaches serving Cunnamulla and Quilpie. <strong>Sleeper</strong> berths and <strong>Economy</strong> seating are available, with meals from the dining car.</p>',
 'transport-queensland-rail-travel-train-timetables-the-westlander-2017',
 'The Westlander — Brisbane to Charleville', 'The Westlander runs Brisbane to Charleville via Toowoomba & Roma, with coach links to Cunnamulla & Quilpie. Sleepers, dining. Route & booking.', 80),

('the-inlander', 'The Inlander', 'Queensland Rail Travel', 'https://www.queenslandrailtravel.com.au/trains/inlander',
 'https://www.queenslandrailtravel.com.au/', ARRAY['qld'], false, false,
 'Townsville ↔ Mount Isa', 'Townsville', 'Mount Isa',
 ARRAY['Townsville','Charters Towers','Hughenden','Cloncurry','Mount Isa'],
 ARRAY['Sleeper','First Class seat','Economy seat'], 'Twice weekly each way', 'About 20 hours',
 'The Inlander crosses the north-west from the tropical coast at Townsville to the mining city of Mount Isa, through Charters Towers and the dinosaur country around Hughenden.',
 '<p>The Inlander links Townsville and Mount Isa twice a week, running inland through the gold-rush town of Charters Towers, Hughenden and Cloncurry. <strong>Sleeper</strong>, <strong>First Class</strong> and <strong>Economy</strong> options are available with dining aboard.</p>',
 'transport-queensland-rail-travel-train-timetables-the-inlander-2029',
 'The Inlander — Townsville to Mount Isa', 'The Inlander runs Townsville to Mount Isa via Charters Towers & Hughenden. Sleepers, dining car. Route, stations & how to book with Queensland Rail.', 90),

('gulflander', 'Gulflander', 'Queensland Rail Travel', 'https://www.queenslandrailtravel.com.au/trains/gulflander',
 'https://www.queenslandrailtravel.com.au/', ARRAY['qld'], false, true,
 'Normanton ↔ Croydon (Gulf Savannah heritage)', 'Normanton', 'Croydon',
 ARRAY['Normanton','Critters Camp','Blackbull','Croydon'],
 ARRAY['Heritage rail car'], 'Weekly + seasonal specials', 'About 5 hours one way',
 'Affectionately called the "Tin Hare", the Gulflander has rattled along its isolated 152 km line between Normanton and Croydon in the Gulf Savannah since 1891.',
 '<p>The Gulflander is one of Australia''s great rail curiosities — a self-contained heritage line that connects to no other railway, running weekly between Normanton and Croydon across the Gulf Savannah. The historic rail motor takes about five hours, with the guard sharing the stories of the line along the way. A bucket-list trip for rail enthusiasts and outback travellers.</p>',
 'transport-queensland-rail-travel-train-timetables-gulflander-2023',
 'Gulflander — Normanton to Croydon Heritage Train', 'The Gulflander "Tin Hare" heritage train runs Normanton to Croydon across the Gulf Savannah. History, route & how to book with Queensland Rail.', 100),

('kuranda-scenic-railway', 'Kuranda Scenic Railway', 'Queensland Rail Travel', 'https://www.ksr.com.au/',
 'https://www.ksr.com.au/', ARRAY['qld'], false, true,
 'Cairns ↔ Kuranda through the rainforest', 'Cairns', 'Kuranda',
 ARRAY['Cairns','Freshwater','Barron Gorge','Kuranda'],
 ARRAY['Heritage Class','Gold Class'], 'Daily services', 'About 1¾ hours each way',
 'A 19th-century engineering marvel — the Kuranda Scenic Railway winds from Cairns up through World Heritage rainforest, past Barron Falls and through 15 hand-cut tunnels to the village of Kuranda.',
 '<p>Built in the 1880s by hand, the Kuranda Scenic Railway is one of Far North Queensland''s signature experiences. The train climbs from Cairns through the Barron Gorge, crossing soaring bridges and passing waterfalls to reach Kuranda. Many visitors pair it with the Skyrail Rainforest Cableway for a loop — train up, gondola down (or vice versa). <strong>Heritage</strong> and premium <strong>Gold Class</strong> services run daily.</p>',
 'transport-queensland-rail-travel-train-timetables-kuranda-scenic-railway-20413',
 'Kuranda Scenic Railway — Cairns to Kuranda', 'The Kuranda Scenic Railway climbs from Cairns through rainforest & Barron Gorge to Kuranda. Pair with Skyrail. Classes, route & booking.', 110),

('savannahlander', 'Savannahlander', 'Savannahlander', 'https://www.savannahlander.com.au/',
 'https://www.savannahlander.com.au/', ARRAY['qld'], false, true,
 'Cairns ↔ Forsayth (Savannah Way by rail)', 'Cairns', 'Forsayth',
 ARRAY['Cairns','Kuranda','Mount Surprise','Einasleigh','Forsayth'],
 ARRAY['Heritage rail car'], 'Weekly multi-day tours (seasonal)', 'Multi-day return',
 'A silver 1960s rail motor that trundles inland from Cairns across the Gulf Savannah to Forsayth, run as a leisurely multi-day outback adventure with overnight stops.',
 '<p>The Savannahlander is a classic 1960s silver rail motor that runs as a multi-day guided tour from Cairns into the Gulf Savannah, with stops at Mount Surprise (for the Undara lava tubes), Einasleigh and Forsayth. It''s slow travel at its best — short hops by day, comfortable accommodation by night. Operates seasonally and books out in advance.</p>',
 NULL,
 'Savannahlander — Cairns to Forsayth Outback Train', 'The Savannahlander is a heritage rail-motor adventure from Cairns to Forsayth across the Gulf Savannah, with stops at Undara & Einasleigh. How to book.', 120),

-- ─── NEW SOUTH WALES — NSW TrainLink ─────────────────────────────────────────
('nsw-trainlink-xpt', 'NSW TrainLink XPT', 'NSW TrainLink', 'https://transportnsw.info/regional',
 'https://transportnsw.info/regional', ARRAY['nsw'], false, false,
 'Sydney ↔ Melbourne, Brisbane & Dubbo', 'Sydney', 'Melbourne / Brisbane',
 ARRAY['Sydney','Albury','Melbourne','Coffs Harbour','Casino','Brisbane','Dubbo'],
 ARRAY['First Class (sleeper/seat)','Economy seat'], 'Daily services', 'Up to ~11–14 hours',
 'The XPT is NSW''s long-distance workhorse, fanning out from Sydney to Melbourne, Brisbane and Dubbo with daytime seats and overnight sleeper berths.',
 '<p>NSW TrainLink''s XPT (Express Passenger Train) runs the state''s major intercity corridors: south to Albury and Melbourne, north along the coast to Coffs Harbour, Grafton, Casino and Brisbane, and west to Dubbo. Overnight services to Melbourne and Brisbane carry <strong>First Class sleeper</strong> cabins as well as <strong>First Class</strong> and <strong>Economy</strong> seating, with a buffet car aboard. A fleet of new regional trains is progressively replacing the XPT.</p>',
 NULL, 'NSW TrainLink XPT — Sydney to Melbourne & Brisbane', 'The NSW TrainLink XPT links Sydney with Melbourne, Brisbane & Dubbo — daytime seats & overnight sleepers. Routes, classes & how to book.', 130),

('nsw-trainlink-xplorer', 'NSW TrainLink Xplorer & Endeavour', 'NSW TrainLink', 'https://transportnsw.info/regional',
 'https://transportnsw.info/regional', ARRAY['nsw'], false, false,
 'Sydney ↔ Canberra, Armidale, Moree & Griffith', 'Sydney', 'Canberra / Armidale',
 ARRAY['Sydney','Goulburn','Canberra','Tamworth','Armidale','Moree'],
 ARRAY['First Class seat','Economy seat'], 'Daily services', 'Varies by route',
 'The Xplorer and Endeavour railcars connect Sydney with Canberra and the regional centres of the north-west and Riverina — Tamworth, Armidale, Moree and Griffith.',
 '<p>NSW TrainLink''s Xplorer fleet runs the daytime regional services that the XPT doesn''t cover: south to Goulburn and Canberra, and north-west to Tamworth, Armidale, Moree and Griffith. <strong>First Class</strong> and <strong>Economy</strong> seating are available, with connecting TrainLink coaches reaching towns beyond the rail network.</p>',
 NULL, 'NSW TrainLink Xplorer — Sydney to Canberra & Regional NSW', 'NSW TrainLink Xplorer railcars link Sydney with Canberra, Tamworth, Armidale, Moree & Griffith. Routes, classes & how to book.', 140),

-- ─── VICTORIA — V/Line ───────────────────────────────────────────────────────
('vline', 'V/Line Regional Trains', 'V/Line', 'https://www.vline.com.au/',
 'https://www.vline.com.au/', ARRAY['vic'], false, false,
 'Melbourne ↔ regional Victoria', 'Melbourne', 'Regional Victoria',
 ARRAY['Geelong','Ballarat','Bendigo','Traralgon','Warrnambool','Albury'],
 ARRAY['First Class','Economy'], 'Frequent daily services', 'Varies by line',
 'V/Line connects Melbourne with every corner of regional Victoria — the Geelong, Ballarat and Bendigo lines run all day, with longer hauls to Warrnambool, Gippsland and Albury.',
 '<p>V/Line is Victoria''s regional network, radiating from Melbourne''s Southern Cross Station to Geelong (and the Great Ocean Road gateway), Ballarat, Bendigo, Seymour, Traralgon and the Gippsland Lakes, Warrnambool, and Albury on the NSW border. The busy commuter corridors run frequently all day; longer regional services offer <strong>First Class</strong> and <strong>Economy</strong>. Coach connections extend to towns off the rail lines. It''s the easy, affordable way to reach regional Victoria without a car.</p>',
 NULL, 'V/Line — Trains to Regional Victoria from Melbourne', 'V/Line connects Melbourne with Geelong, Ballarat, Bendigo, Gippsland, Warrnambool & Albury. Lines, classes & how to plan a regional Victoria trip.', 150),

-- ─── WESTERN AUSTRALIA — Transwa ─────────────────────────────────────────────
('prospector', 'Prospector', 'Transwa', 'https://www.transwa.wa.gov.au/',
 'https://www.transwa.wa.gov.au/', ARRAY['wa'], false, false,
 'Perth ↔ Kalgoorlie (the Goldfields)', 'Perth', 'Kalgoorlie',
 ARRAY['Perth','Northam','Merredin','Southern Cross','Kalgoorlie'],
 ARRAY['Economy seat'], 'Daily services', 'About 7 hours',
 'Transwa''s fast Prospector railcar links Perth with the historic goldfields city of Kalgoorlie-Boulder, crossing the Wheatbelt in a single day.',
 '<p>The Prospector is Western Australia''s long-distance train, running from East Perth across the Wheatbelt through Northam and Merredin to Kalgoorlie. Comfortable reclining seats, an onboard buffet and at-seat service make it an easy day trip into the goldfields. Connecting Transwa coaches serve the wider region.</p>',
 NULL, 'Prospector — Perth to Kalgoorlie Train', 'The Transwa Prospector runs Perth to Kalgoorlie across the Wheatbelt in a day. Route, stations, onboard service & how to book.', 160),

('australind', 'Australind', 'Transwa', 'https://www.transwa.wa.gov.au/',
 'https://www.transwa.wa.gov.au/', ARRAY['wa'], false, false,
 'Perth ↔ Bunbury (the South West)', 'Perth', 'Bunbury',
 ARRAY['Perth','Pinjarra','Harvey','Bunbury'],
 ARRAY['Economy seat'], 'Daily services', 'About 2½ hours',
 'The Australind runs south from Perth to the port city of Bunbury, the gateway to WA''s South West wine and coastal country.',
 '<p>The Australind links Perth and Bunbury daily, calling at Pinjarra and Harvey along the way. From Bunbury, Transwa coaches connect to Margaret River, Augusta, Albany and the South West''s beaches, forests and wineries — making the train a handy first leg of a South West road-free getaway.</p>',
 NULL, 'Australind — Perth to Bunbury Train', 'The Transwa Australind runs Perth to Bunbury daily, the gateway to WA''s South West. Route, coach connections & how to book.', 170),

('avonlink-merredinlink', 'AvonLink & MerredinLink', 'Transwa', 'https://www.transwa.wa.gov.au/',
 'https://www.transwa.wa.gov.au/', ARRAY['wa'], false, false,
 'Perth ↔ Northam & Merredin (Avon Valley & Wheatbelt)', 'Perth', 'Northam / Merredin',
 ARRAY['Perth','Toodyay','Northam','Merredin'],
 ARRAY['Economy seat'], 'Weekly services', 'About 1½–3½ hours',
 'Transwa''s AvonLink and MerredinLink railcars serve the Avon Valley and central Wheatbelt towns of Toodyay, Northam and Merredin.',
 '<p>The AvonLink connects Perth with the Avon Valley towns of Toodyay and Northam, while the MerredinLink continues into the central Wheatbelt to Merredin. They''re scenic, low-key services through the hills and farmland east of Perth, with connecting coaches to surrounding towns.</p>',
 NULL, 'AvonLink & MerredinLink — Perth to the Avon Valley & Wheatbelt', 'Transwa''s AvonLink & MerredinLink trains serve Toodyay, Northam & Merredin east of Perth. Routes, frequency & how to book.', 180),

-- ─── SOUTH AUSTRALIA — heritage ──────────────────────────────────────────────
('pichi-richi-railway', 'Pichi Richi Railway', 'Pichi Richi Railway Preservation Society', 'https://pichirichirailway.org.au/',
 'https://pichirichirailway.org.au/', ARRAY['sa'], false, true,
 'Quorn ↔ Port Augusta through the Flinders Ranges', 'Quorn', 'Port Augusta',
 ARRAY['Quorn','Woolshed Flat','Port Augusta'],
 ARRAY['Heritage carriage'], 'Seasonal — April to November', 'Half-day return',
 'A lovingly restored section of the original Ghan line, the Pichi Richi Railway runs vintage steam and heritage trains through the Pichi Richi Pass in the southern Flinders Ranges.',
 '<p>The Pichi Richi Railway preserves a surviving stretch of the original narrow-gauge Ghan route, running heritage steam and diesel services between Quorn and Port Augusta through the dramatic Pichi Richi Pass. Operated by volunteers, it runs on selected days from April to November and is one of the best-preserved working heritage railways in Australia — a perfect add-on to a Flinders Ranges trip.</p>',
 NULL, 'Pichi Richi Railway — Heritage Trains in the Flinders Ranges', 'The Pichi Richi Railway runs vintage steam & heritage trains Quorn to Port Augusta through the Flinders Ranges. Season, route & how to book.', 190),

-- ─── TASMANIA — heritage (no scheduled passenger rail) ───────────────────────
('west-coast-wilderness-railway', 'West Coast Wilderness Railway', 'West Coast Wilderness Railway', 'https://www.wcwr.com.au/',
 'https://www.wcwr.com.au/', ARRAY['tas'], false, true,
 'Queenstown ↔ Strahan through Tasmanian rainforest', 'Queenstown', 'Strahan',
 ARRAY['Queenstown','Dubbil Barril','Strahan'],
 ARRAY['Heritage Carriage','Wilderness Carriage'], 'Seasonal daily departures', 'Half-day to full-day',
 'A reconstructed 1890s rack-and-pinion mountain railway that hauls original steam locomotives through the rainforest and river gorges of Tasmania''s wild West Coast.',
 '<p>Tasmania has no scheduled long-distance passenger trains, but the West Coast Wilderness Railway is a destination in its own right. Restored steam locomotives use a rare rack-and-pinion system to climb the steep grades between the mining town of Queenstown and the harbour village of Strahan, crossing the King River gorge and stopping in dense rainforest. Several itineraries run, from half-day rainforest trips to the full Queenstown–Strahan journey.</p>',
 NULL, 'West Coast Wilderness Railway — Queenstown to Strahan', 'Tasmania''s West Coast Wilderness Railway runs restored steam trains Queenstown to Strahan through rainforest & river gorges. Trips, route & booking.', 200)

ON CONFLICT (slug) DO UPDATE SET
  name=EXCLUDED.name, operator=EXCLUDED.operator, operator_url=EXCLUDED.operator_url,
  booking_url=EXCLUDED.booking_url, state_codes=EXCLUDED.state_codes, is_national=EXCLUDED.is_national,
  is_heritage=EXCLUDED.is_heritage, route_summary=EXCLUDED.route_summary, from_city=EXCLUDED.from_city,
  to_city=EXCLUDED.to_city, key_stations=EXCLUDED.key_stations, classes=EXCLUDED.classes,
  frequency=EXCLUDED.frequency, duration_label=EXCLUDED.duration_label, intro=EXCLUDED.intro,
  body_html=EXCLUDED.body_html, legacy_article_slug=EXCLUDED.legacy_article_slug,
  seo_title=EXCLUDED.seo_title, seo_description=EXCLUDED.seo_description,
  display_order=EXCLUDED.display_order, updated_at=now();
